openapi: 3.0.0
info:
  title: milkymoney
  description: 奶牛挣闲钱系统分析与设计
  version: 0.0.0

paths:
  /task:
    get:
      summary: 查询已发布任务列表
      parameters: 
        - in: query
          name: page
          schema:
            type: integer
          description: 任务列表的第几页
          required: true
        - in: query
          name: labels
          schema:
            $ref: '#/components/schemas/Labels'
          description: 筛选的标签列表，每一条记录是一条标签，标签格式为“key:value”
      responses:
        '200':
          description: 返回符合条件的已发布任务列表
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      summary: 发布任务
      description: 用户发送发布任务的请求
      requestBody:
        description: 发送待发布的任务
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/Task'
                - $ref: '#/components/schemas/WXcode'
      responses:
        '200':
          description: 服务器正常返回
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: 描述发布是否成功
                  id: 
                    type: integer
                    description: 已发布任务的id
                  message:
                    type: string
                    description: 描述错误信息
          
  /task/{taskId}:
    get:
      summary: 查询指定id的任务
      parameters: 
        - in: path
          name: taskId
          schema:
            type: integer
          required: true
          description: 待查询任务id
      responses:
        '200':
          description: 返回被查询的任务
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: 表示是否有指定id的任务
                  task:
                    description: 被查询的任务，当查询失败时，返回空
                    $ref: '#/components/schemas/Task'
        
  /task/accept:
    put:
      summary: 接受任务
      requestBody:
        description: 发送待发布的任务
        required: true
        content:
          application/json:
            schema:
              allOf:
                - type: object
                  properties:
                    userId:
                      type: integer
                      description: 接受者id
                    taskId:
                      type: integer
                      description: 接受任务的id
                - $ref: '#/components/schemas/WXcode'
      responses:
        '200':
          description: 服务器返回结果
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: 描述是否成功接受
                  message:
                    type: string
                    description: 描述错误信息
  
  /task/settleup:
    put:
      summary: 结算任务
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - type: object
                  properties:
                    userId:
                      type: integer
                      description: 接受者id
                    taskId:
                      type: integer
                      description: 接受任务的id
                - $ref: '#/components/schemas/WXcode'
          img/png:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: 服务器返回结果
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: 描述是否成功结算
                  message:
                    type: string
                    description: 描述错误信息
  
  /user:
    post:
      summary: 查询用户信息
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WXcode'
      responses:
        '200':
          description: 返回用户信息
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
  
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        password:
          type: string
          writeOnly: true
        balance:
          type: integer
    Task:
      type: object
      properties:
        tid:
          description: 任务id
          type: integer
        type:
          description: 任务类型
          type: string
        description:
          description: 任务描述
          type: string
        reward:
          description: 任务报酬
          type: integer
        deadline:
          description: 任务DDL
          type: string
        label:
          description: 任务标列表
          $ref: '#/components/schemas/Labels'
        state:
          type: string
          description: 任务的状态
          enum:
            - opened
            - closed
        priority:
          description: 任务优先级
          type: integer
        maxAccept:
          description: 最大接受人数
          type: integer
        hasAccept:
          description: 已接受人数
          type: integer
    Labels:
      type: array
      description: 标签列表，每一条记录是一条标签，标签格式为“key:value”
      items:
        type: string
 
    # code:
    #   description: 微信提供认证code
    #   type: string
    WXcode:
      type: object
      properties:
        code:
          description: 微信提供认证code
          type: string